name: "NAME"
version: "VERSION"
main: "MAIN"
api-version: 1.13
authors: [AUTHORS]
description: "DESCRIPTION"
commands:
  info:
    aliases: [ALIASES]
    description: "DESCRIPTION"
    permission-message: "PERMISSION MESSAGE"
    usage: "USAGE"
permissions:
